name: CI

on:
  pull_request:
  push:
    branches:
      - "*main"

env: 
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust project - latest
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os:
          - ubuntu
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose
      - run: cargo test --verbose --features service_checker
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Lint (ultra-minimal)
      run: make clippy-minimal ARGS='--manifest-path Cargo.toml'
    - name: Lint (minimal)
      run: make clippy-minimal
    - name: Lint (all)
      run: make clippy-full
    - name: Lint (release)
      run: make clippy-release
