name: Publish

on:
  pull_request:
  push:
    branches:
      - "*release"

env: 
  CARGO_TERM_COLOR: always



jobs:
  publish:
    name: Publish to Crates.io
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os:
          - ubuntu
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}      
